source "https://rubygems.org"

gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.8'
gem 'puppetlabs_spec_helper'
gem 'rspec-puppet', :git => 'https://github.com/rodjek/rspec-puppet.git'
# ruby 1.8 braucht rspec < 3.2
gem 'rspec', '~> 3.1.0', :platforms => :ruby_18

# optional
gem 'metadata-json-lint'
gem 'rspec-puppet-facts'

gem 'puppet-lint-absolute_classname-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-version_comparison-check'
gem 'puppet-lint-classes_and_types_beginning_with_digits-check'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-resource_reference_syntax'

# see http://puppet.community/ for more extensions


## integration tests

group :system_tests do
  gem 'beaker' if RUBY_VERSION >= '1.9'
  gem 'beaker-rspec' if RUBY_VERSION >= '1.9'
  gem 'beaker-puppet_install_helper' if RUBY_VERSION >= '1.9'
end

